version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env
  db:
    image: "postgres:alpine"
    restart: always
    ports:
      - "5432:5432"
